### ISSUE TITLE
CSRF Issue

### ISSUE THREAD

**Issue by gridworkz** [RamezIssac/django-erp-framework#13]
Hi:

After a fresh install I'm getting a CSRF token error when trying to login with super user:

....
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'jazzy_admin_url'
...

In template /home/osboxes/.local/lib/python3.6/site-packages/ra/admin/templates/ra/sidebar.html, error at line **24**

Cheers,
Dave

**Comment by luki922** [comment]
Solution to the problem can be found in the ticket: #16

**Comment by gridworkz** [comment]
Now I get - Invalid filter: request
