### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by seun-otosho** [RamezIssac/django-erp-framework#25]
Hi 

Been trying to install using the instructions both as a standalone and integrating into an existing system

I keep getting this error

`django.core.exceptions.ImproperlyConfigured: The app label 'ra.admin' is not a valid Python identifier.`

Kindly assist

Cheers

**Comment by faizasaeed97** [comment]
Hey, I am facing the same issue, did you find a solution?

**Comment by yousefshalby** [comment]
Did you find a solution ? because I have the same problem ?

**Comment by seun-otosho** [comment]
Not yet, problems still persist

Please share if you have a solution.

**Comment by EchoMed07** [comment]
same issue, no solution yet?

**Comment by RamezIssac** [comment]
Hello All 
Apologize for the over due late reply.. 
This is because of the support of app names ... Issuing a fixing release soon.

**Comment by RamezIssac** [comment]
Should be solved by https://pypi.org/project/django-ra-erp/1.3.1/

**Comment by DrGhonzo** [comment]
Hi, I've been trying to install following the steps on pypi from terminal and from embedded terminal in pycharm, with next error:

ERROR: Command errored out with exit status 1:
     command: 'c:\users\dr.ghonzo\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\D
RC658~1.GHO\\AppData\\Local\\Temp\\pip-install-3wl2mdsb\\rcssmin_6c2958cc1375429b9db272838a38438a\\setup.py'"'"'; __file__='"'"'C:\\Users\\DRC658~1.GHO\\AppData\\Loc
al\\Temp\\pip-install-3wl2mdsb\\rcssmin_6c2958cc1375429b9db272838a38438a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__fil
e__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '
"'"'exec'"'"'))' install --record 'C:\Users\DRC658~1.GHO\AppData\Local\Temp\pip-record-qgvm2ewy\install-record.txt' --single-version-externally-managed --compile --i
nstall-headers 'c:\users\dr.ghonzo\appdata\local\programs\python\python37\Include\rcssmin'
         cwd: C:\Users\DRC658~1.GHO\AppData\Local\Temp\pip-install-3wl2mdsb\rcssmin_6c2958cc1375429b9db272838a38438a\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying .\rcssmin.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_rcssmin' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dr.ghonzo\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize
; sys.argv[0] = '"'"'C:\\Users\\DRC658~1.GHO\\AppData\\Local\\Temp\\pip-install-3wl2mdsb\\rcssmin_6c2958cc1375429b9db272838a38438a\\setup.py'"'"'; __file__='"'"'C:\\
Users\\DRC658~1.GHO\\AppData\\Local\\Temp\\pip-install-3wl2mdsb\\rcssmin_6c2958cc1375429b9db272838a38438a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(
__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close
();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DRC658~1.GHO\AppData\Local\Temp\pip-record-qgvm2ewy\install-record.txt' --single-version
-externally-managed --compile --install-headers 'c:\users\dr.ghonzo\appdata\local\programs\python\python37\Include\rcssmin' Check the logs for full command output.

Any suggestion?

**Comment by RamezIssac** [comment]
Hello
there is a solution in the log asking yo to get windows c++ , probably for compiling some a package. This may will solve it.

**Comment by tusharsharma27** [comment]
can you provide support for Django 4? I am getting several package errors while running  ./manage.py migrate   for which i although getting solutions but stuck at following:

File "----/-/erp/nams/nams/urls.py", line 24, in <module>
    path('', ra_admin_site.urls),
             ^^^^^^^^^^^^^^^^^^
  File "/---/-/erp/ra-erp/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 318, in urls
    return self.get_urls(), "admin", self.name
           ^^^^^^^^^^^^^^^
  File "---/-/erp/ra-erp/lib/python3.11/site-packages/ra/admin/base.py", line 73, in get_urls
    url(r'^i18n/', include('django.conf.urls.i18n')),
    ^^^
NameError: name 'url' is not defined. Did you mean: 'urls'?

**Comment by RamezIssac** [comment]
Hello
There is a new version released in which these issue were addressed .
Demo site: https://my-shop.django-erp-framework.com/
Pypi: Django-erp-framerwork
