### ISSUE TITLE
Charts are not shown

### ISSUE THREAD

**Issue by ChaoticPlex** [RamezIssac/django-erp-framework#28]
Hi, 

Just tried to implement the sample you have included into the documentation. got to the "Adding charts" and faced this error. maybe you could help me resolve it? 

her is the output of chrome console on refreshing the report page (Django does not output any error itself):

![image](https://user-images.githubusercontent.com/449706/153759127-a3f40260-011e-4eee-b540-83f716c08de6.png)

here is my pip freeze output in case you wanted to reproduce it yourself
```
asgiref==3.5.0
dateutils==0.6.7
Django==2.2.13
django-appconf==1.0.5
django-compressor==2.3
django-crequest==2018.5.11
django-crispy-forms==1.8.0
django-jazzmin==2.4.9
django-polymorphic==3.1.0
django-ra-erp==1.3.1
django-reversion==4.0.2
django-slick-reporting==0.6.3
django-tabular-permissions==2.9
django-utils-six==2.0
psycopg2-binary==2.9.3
python-dateutil==2.8.2
python-memcached==1.59
pytz==2021.3
rcssmin==1.0.6
rjsmin==1.1.0
simplejson==3.17.6
six==1.16.0
sqlparse==0.4.2
swapper==1.1.1
typing_extensions==4.0.1
unicodecsv==0.14.1
```

**Comment by RamezIssac** [comment]
There is an updated version released .. you can see it in action at https://my-shop.django-erp-framework.com/
