### ISSUE TITLE
Django >4.0 compatibility.  ugettext_lazy > gettext_lazy

### ISSUE THREAD

**Issue by AndrejGorodnij** [RamezIssac/django-erp-framework#32]
`ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/rusty/ra-django/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py)`

Because of removing `ugettext_lazy` from Django 4.0 version, and higher, you need to add check for this import, and change old version :

`from django.utils.translation import ugettext_lazy as _`

to new

`from django.utils.translation import gettext_lazy as _`

Same story with `ImportError: cannot import name 'force_text' from 'django.utils.encoding'`

Django 4.0+ use `force_str` instead of `force_text`

**Comment by daym** [comment]
https://github.com/ra-systems/django-ra-erp/pull/30

**Comment by RamezIssac** [comment]
Hello :wave: 
This issue is fixed in the new release.
