### ISSUE TITLE
Can't install with pip install

### ISSUE THREAD

**Issue by BalighMehrez** [RamezIssac/django-erp-framework#33]
When trying pip install django-ra-erp, I have gotten the following error
<img width="650" alt="image" src="https://user-images.githubusercontent.com/2021146/229469352-c4ea1874-6226-44e6-a36b-70320d7fe1c5.png">
we need to fix this line
https://github.com/ra-systems/django-ra-erp/blob/554fcbd9f3f97a9bfd5f1e88c3323c8c50f77182/setup.cfg#L59

**Comment by AndrejGorodnij** [comment]
I think there is 1 extra ` = ` symbol there, it must be `>=, == , <=`, not ` >== `

**Comment by RamezIssac** [comment]
There is a new release now, it's with a make over  Pypi: "django-erp-framework"

demo https://my-shop.django-erp-framework.com/
